-- CREACION DE TODAS LAS TABLAS DE EL SISTEMA 
-- ENTIDADES FUERTES 

CREATE DATABASE IF NOT EXISTS SGP_VIVIT;

USE SGP_VIVIT;



CREATE TABLE TBSGP_A_DEPARTAMENTO (
	TN_DEP_ID           INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TC_DEP_NOMBRE       VARCHAR(255) NOT NULL,
    TC_DEP_DESCRIPCION  VARCHAR(255) NOT NULL
    );

CREATE TABLE TBSGP_A_ROL (
	TN_ROL_ID           INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TC_ROL_NOMBRE       VARCHAR(255) NOT NULL,
    TC_ROL_DESCRIPCION  VARCHAR(255) NOT NULL
    );


CREATE TABLE TBSGP_A_ESTADO_SOLICITUD(

	TN_EST_ID          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TC_EST_NOMBRE      VARCHAR(255) NOT NULL,
    TC_EST_DESCRIPCION VARCHAR(255) NOT NULL
);


-- CREACION DE LAS ENTIDADES DEBILES 

-- USUARIOS 
CREATE TABLE TBSGP_A_USUARIO (

	TN_USU_ID              INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TN_DEP_ID              INT NOT NULL ,
    TN_ROL_ID              INT NOT NULL,
    
    
    TC_USU_NOMBRE           VARCHAR(255) NOT NULL,
    TC_USU_APELLIDOS        VARCHAR(255) NOT NULL,
    TC_USU_IDENTIFICACION   VARCHAR(255) NOT NULL,
    TC_USU_CORREO           VARCHAR(255) NOT NULL,
    TC_USU_PASSWORD         VARCHAR(255) NOT NULL,
    TF_USU_FECHA_NACIMIENTO DATE NOT NULL,
    
   FOREIGN KEY (TN_DEP_ID) REFERENCES TBSGP_A_DEPARTAMENTO(TN_DEP_ID),
   FOREIGN KEY (TN_ROL_ID) REFERENCES TBSGP_A_ROL(TN_ROL_ID)
    

);

-- PERMISOS 

CREATE TABLE TBSGP_H_SOLICITUD_PERMISO (

	TN_SOL_ID               INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    TN_EST_ID               INT NOT NULL,
    TN_USU_ID               INT NOT NULL,
    
    TC_SOL_MOTIVO           VARCHAR(500),
    TF_SOL_FECHA_INICIO     DATE,
    TF_SOL_FECHA_FIN        DATE,
    
    
    FOREIGN KEY (TN_EST_ID) REFERENCES TBSGP_A_ESTADO_SOLICITUD(TN_EST_ID),
    FOREIGN KEY (TN_USU_ID) REFERENCES TBSGP_A_USUARIO(TN_USU_ID)
);



-- INSERT EN LA TABLA DEPARTAMENTO

INSERT INTO TBSGP_A_DEPARTAMENTO (TC_DEP_NOMBRE, TC_DEP_DESCRIPCION) VALUES ('Recursos Humanos','Gestión del personal de la empresa');
INSERT INTO TBSGP_A_DEPARTAMENTO (TC_DEP_NOMBRE, TC_DEP_DESCRIPCION) VALUES ('Tecnología','Desarrollo y soporte de sistemas');
INSERT INTO TBSGP_A_DEPARTAMENTO (TC_DEP_NOMBRE, TC_DEP_DESCRIPCION) VALUES ('Finanzas','Administración de recursos financieros');
INSERT INTO TBSGP_A_DEPARTAMENTO (TC_DEP_NOMBRE, TC_DEP_DESCRIPCION) VALUES ('Ventas','Gestión de ventas y clientes');
INSERT INTO TBSGP_A_DEPARTAMENTO (TC_DEP_NOMBRE, TC_DEP_DESCRIPCION) VALUES ('Operaciones','Control de procesos operativos');

-- INSERT EN LA TABLA DE ROL (2 ROLES)

INSERT INTO TBSGP_A_ROL (TC_ROL_NOMBRE, TC_ROL_DESCRIPCION) VALUES ('Administrador','Control total del sistema');
INSERT INTO TBSGP_A_ROL (TC_ROL_NOMBRE, TC_ROL_DESCRIPCION) VALUES ('Empleado','Usuario que solicita permisos');

-- INSERT EN LA TABLA DE ESTADO DE PERMISO 

INSERT INTO TBSGP_A_ESTADO_SOLICITUD (TC_EST_NOMBRE, TC_EST_DESCRIPCION) VALUES ('Pendiente','Solicitud enviada esperando aprobación');
INSERT INTO TBSGP_A_ESTADO_SOLICITUD (TC_EST_NOMBRE, TC_EST_DESCRIPCION) VALUES ('Aprobado','Solicitud aprobada');
INSERT INTO TBSGP_A_ESTADO_SOLICITUD (TC_EST_NOMBRE, TC_EST_DESCRIPCION) VALUES ('Rechazado','Solicitud denegada');


-- INSERT EN LA TABLA DE USUARIOS 
INSERT INTO TBSGP_A_USUARIO (TN_DEP_ID, TN_ROL_ID, TC_USU_NOMBRE, TC_USU_APELLIDOS, TC_USU_IDENTIFICACION, TC_USU_CORREO, TC_USU_PASSWORD, TF_USU_FECHA_NACIMIENTO) VALUES (1,2,'Carlos','Ramírez','101110111','carlos@vivit.com','123456','1990-05-10');
INSERT INTO TBSGP_A_USUARIO (TN_DEP_ID, TN_ROL_ID, TC_USU_NOMBRE, TC_USU_APELLIDOS, TC_USU_IDENTIFICACION, TC_USU_CORREO, TC_USU_PASSWORD, TF_USU_FECHA_NACIMIENTO) VALUES (2,2,'Ana','Gómez','202220222','ana@vivit.com','123456','1992-08-15');
INSERT INTO TBSGP_A_USUARIO (TN_DEP_ID, TN_ROL_ID, TC_USU_NOMBRE, TC_USU_APELLIDOS, TC_USU_IDENTIFICACION, TC_USU_CORREO, TC_USU_PASSWORD, TF_USU_FECHA_NACIMIENTO) VALUES (3,2,'Luis','Martínez','303330333','luis@vivt.com','123456','1988-03-21');
INSERT INTO TBSGP_A_USUARIO (TN_DEP_ID, TN_ROL_ID, TC_USU_NOMBRE, TC_USU_APELLIDOS, TC_USU_IDENTIFICACION, TC_USU_CORREO, TC_USU_PASSWORD, TF_USU_FECHA_NACIMIENTO) VALUES (4,2,'María','Fernández','404440444','maria@vivit.com','123456','1995-11-30');
INSERT INTO TBSGP_A_USUARIO (TN_DEP_ID, TN_ROL_ID, TC_USU_NOMBRE, TC_USU_APELLIDOS, TC_USU_IDENTIFICACION, TC_USU_CORREO, TC_USU_PASSWORD, TF_USU_FECHA_NACIMIENTO) VALUES (5,1,'Pedro','Sánchez','505550555','pedro@vivit.com','123456','1985-01-12');

-- INSERT EN LAS TABLAS DE SOLICITUD DE PERMISOS

INSERT INTO TBSGP_H_SOLICITUD_PERMISO (TN_EST_ID, TN_USU_ID, TC_SOL_MOTIVO, TF_SOL_FECHA_INICIO, TF_SOL_FECHA_FIN) VALUES (1,1,'Cita médica','2026-03-10','2026-03-10');
INSERT INTO TBSGP_H_SOLICITUD_PERMISO (TN_EST_ID, TN_USU_ID, TC_SOL_MOTIVO, TF_SOL_FECHA_INICIO, TF_SOL_FECHA_FIN) VALUES (2,2,'Vacaciones familiares','2026-04-01','2026-04-07');
INSERT INTO TBSGP_H_SOLICITUD_PERMISO (TN_EST_ID, TN_USU_ID, TC_SOL_MOTIVO, TF_SOL_FECHA_INICIO, TF_SOL_FECHA_FIN) VALUES (3,3,'Asuntos personales','2026-03-15','2026-03-16');
INSERT INTO TBSGP_H_SOLICITUD_PERMISO (TN_EST_ID, TN_USU_ID, TC_SOL_MOTIVO, TF_SOL_FECHA_INICIO, TF_SOL_FECHA_FIN) VALUES (1,4,'Trámite bancario','2026-03-20','2026-03-20');
INSERT INTO TBSGP_H_SOLICITUD_PERMISO (TN_EST_ID, TN_USU_ID, TC_SOL_MOTIVO, TF_SOL_FECHA_INICIO, TF_SOL_FECHA_FIN) VALUES (1,5,'Capacitación laboral','2026-05-05','2026-05-07');



